// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBud_CrBBtYSBx-5j3f7NhEWt9p44_kAeM',
    appId: '1:450602968082:web:e872ac38e02431aff164cb',
    messagingSenderId: '450602968082',
    projectId: 'hadrmout-ee44e',
    authDomain: 'hadrmout-ee44e.firebaseapp.com',
    storageBucket: 'hadrmout-ee44e.appspot.com',
    measurementId: 'G-X0CJ8QSY51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqIHNcazNfp-_NeWpG7F5lJ05pyeF97ik',
    appId: '1:450602968082:android:54aacd0c16974ff3f164cb',
    messagingSenderId: '450602968082',
    projectId: 'hadrmout-ee44e',
    storageBucket: 'hadrmout-ee44e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV-f-6zopQQYhl_zasv-5t4VLx8ECbnK8',
    appId: '1:450602968082:ios:2cf323d8994c3b31f164cb',
    messagingSenderId: '450602968082',
    projectId: 'hadrmout-ee44e',
    storageBucket: 'hadrmout-ee44e.appspot.com',
    iosBundleId: 'com.example.hadramoutdash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV-f-6zopQQYhl_zasv-5t4VLx8ECbnK8',
    appId: '1:450602968082:ios:bf8477bc372bf71af164cb',
    messagingSenderId: '450602968082',
    projectId: 'hadrmout-ee44e',
    storageBucket: 'hadrmout-ee44e.appspot.com',
    iosBundleId: 'com.example.hadramoutdash.RunnerTests',
  );
}
